[package]
name = "bill-manager"
version = "0.1.0"
edition = "2021"
authors = ["SHA888 <kresnasucandra@gmail.com>"]
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
